name: Portfolio Deployment

on:
  push:
    branches:
      - main
      - test
      - feature

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set S3 Target Folder
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "S3_FOLDER=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "S3_FOLDER=test" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "S3_FOLDER=main" >> $GITHUB_ENV
          fi

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://mohit-ki-demo2/$S3_FOLDER --delete
